<?php
/** @var \Riverstone\OrderArchive\Block\Archiveorder\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $escaper->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $escaper->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $escaper->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $escaper->escapeHtml(__('Order #')) ?>" class="col id"><?= $escaper->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $escaper->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>" class="col status"><?= $escaper->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $escaper->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $escaper->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <a href="#" data-post='<?= /* @noEscape */
                                $block->getPostHelper($block->getUnarchiveUrl($_order))
                            ?>' class="action order">
                                    <span><?= $escaper->escapeHtml(__('Unarchive Order')) ?></span>
                            </a>
                            <?php if ($block->isReorder($_order->getEntityId())): ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $block->getPostHelper($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $escaper->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
